<a href="https://colab.research.google.com/github/KamilBienias/neural-network-course/blob/main/02_basics/02_activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis treści:
1. [Funkcje aktywacji](#a0)
    1. [Import bibliotek](#a1)
    2. [ReLU Function - Rectified Linear Unit](#a2)
    3. [Funkcja Sigmoid](#a3)
    4. [Tanh Function](#a4)
    5. [Funkcja Softmax](#a5)
  

### <a name='a0'></a> 1. Funkcje Aktywacji
#### <a name='a1'></a> 1.1 Import bibliotek

In [ ]:
# ######################################################
# Etap 5. Odcinek: Funkcja aktywacji.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$


In [ ]:
def max_relu(x):
    return max(x, 0.0)

In [ ]:
for i in [-10., -5., 0., 5., 10.]:
    print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [ ]:
# 50 liczb z rozkładu N(0,1)
data = np.random.randn(50)
# sortuje losowe dane
data = sorted(data)
data

[-2.3159024209912222,
 -2.0642705413842775,
 -1.948023060297861,
 -1.9314828750448096,
 -1.8569037132225332,
 -1.6791648051702721,
 -1.396162215319866,
 -1.1842562706692088,
 -1.0749985234351969,
 -0.9896708220353061,
 -0.9201083183853794,
 -0.911267457892984,
 -0.8605015756354312,
 -0.8041944866703535,
 -0.665907902261263,
 -0.6065027704851187,
 -0.548280992273387,
 -0.5135585482201352,
 -0.5086150796723039,
 -0.4799116880842628,
 -0.47275992536730604,
 -0.29337227190246323,
 -0.2558770674549793,
 -0.16206283206278427,
 -0.10942149160877826,
 -0.09828684980534977,
 -0.06748602965673466,
 -0.03550199205526672,
 0.08313890656711628,
 0.11361883685275921,
 0.2141213249929331,
 0.22170812352707348,
 0.24900121567804415,
 0.2641048218471183,
 0.273880250203708,
 0.28338704606112436,
 0.28467592114491413,
 0.31741903105892183,
 0.3333039249278907,
 0.40569122498808524,
 0.4261299420935601,
 0.5650765145441613,
 0.5808021804552801,
 0.7596261149549868,
 1.3706857116796352,
 1.407916949146357

In [ ]:
# wygenerowanie danych do wykresu
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data
# ujemne dane zamienia na zera

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.083139, 0.113619,
       0.214121, 0.221708, 0.249001, 0.264105, 0.27388 , 0.283387,
       0.284676, 0.317419, 0.333304, 0.405691, 0.42613 , 0.565077,
       0.580802, 0.759626, 1.370686, 1.407917, 1.684023, 1.822497,
       2.127262, 2.246934])

In [ ]:
df = pd.DataFrame({'data': data, 
                   'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -2.315902            0.0
1 -2.064271            0.0
2 -1.948023            0.0
3 -1.931483            0.0
4 -1.856904            0.0

In [ ]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='ReLU Function')

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$
Ogólnie $f(x) = \frac{1}{1 + e^{-\beta x}}$
ale u nas $\beta=1$ 

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
# funkcja sigmoid zwraca wartości z przedziału (0,1), które możemy interpretować jako p-two
# a więc warto ją stosować w ostatniej warstwie sieci neuronowej
for i in [-5., -3., -1., 0., 1., 3., 5.]:
    print("sigmoid(" + str(i) + ") = " +  str(sigmoid(i)))

sigmoid(-5.0) = 0.0066928509242848554
sigmoid(-3.0) = 0.04742587317756678
sigmoid(-1.0) = 0.2689414213699951
sigmoid(0.0) = 0.5
sigmoid(1.0) = 0.7310585786300049
sigmoid(3.0) = 0.9525741268224334
sigmoid(5.0) = 0.9933071490757153


In [ ]:
# 50 liczb z rozkładu N(0,3)
data = 3 * np.random.randn(50)
data = sorted(data)
data

[-5.964219666031279,
 -5.797977695224489,
 -5.3009285947912,
 -3.930091767884548,
 -3.574519788899213,
 -3.060766396266093,
 -2.72373582206935,
 -2.707345966505623,
 -2.5899728865053926,
 -2.2974382870562504,
 -2.09871935624736,
 -1.9483576323130816,
 -1.91615772197513,
 -1.675695127630541,
 -1.6361014132730154,
 -1.584257903551738,
 -1.5117903691414432,
 -1.4895239383213608,
 -1.412212892844361,
 -1.3269946987558774,
 -1.262885443046712,
 -0.9768953990602374,
 -0.9613563133850951,
 -0.9347442748606436,
 -0.8541896552886117,
 -0.8117845819158095,
 -0.6583363939455484,
 -0.6303395666083325,
 -0.5886874015450951,
 -0.38887153039924244,
 -0.336775141600107,
 0.19136042100250317,
 0.4138792641243957,
 0.8245830820144147,
 0.871409791154293,
 1.1979268382625476,
 1.4328546563598294,
 1.4740267459384098,
 1.5691254602938116,
 1.864738758415743,
 2.0845944683806468,
 2.1644292403596146,
 2.204750948981646,
 2.2193906502697773,
 2.2195231563436577,
 2.4869098586679748,
 2.8787700685894313,
 3.

In [ ]:
# działam funkcją sigmoid na danych ze zbioru data, który jest posortowany
sigmoid_data = [sigmoid(x) for x in data]
sigmoid_data

[0.0025624654431504086,
 0.0030245081780972704,
 0.004962214520496273,
 0.019263498838012896,
 0.027264683712055354,
 0.04475492670144715,
 0.061587203391116375,
 0.06254127646157447,
 0.06978654296600592,
 0.09133534331012146,
 0.10922135531282509,
 0.12473255211751706,
 0.12829064320707337,
 0.15766634676801589,
 0.16299624223531198,
 0.1701933040443562,
 0.1806736120937071,
 0.18399319242350334,
 0.19588525967648032,
 0.20965691178940163,
 0.22047757920109817,
 0.2735082385009766,
 0.27660672053564783,
 0.28196319602920356,
 0.29855472090463536,
 0.30751034254020587,
 0.34111341652444505,
 0.34743354609716337,
 0.3569360819836997,
 0.4039889862763794,
 0.41659304578764816,
 0.5476946505519488,
 0.6020176878258682,
 0.6952083342409091,
 0.70503896151375,
 0.7681557742578173,
 0.8073457146526922,
 0.8136686601753029,
 0.8276588999758584,
 0.8658483334039841,
 0.8893968009840572,
 0.8970094573617644,
 0.9006753371248721,
 0.901977333714283,
 0.9019890485118724,
 0.9232190422655435,
 0.

In [ ]:
df = pd.DataFrame({'data': data, 
                   'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -5.964220      0.002562
1 -5.797978      0.003025
2 -5.300929      0.004962
3 -3.930092      0.019263
4 -3.574520      0.027265

In [ ]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [ ]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [ ]:
# 100 liczb z rozkładu N(0,2)
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-6.621051889461325,
 -6.479169639714347,
 -5.25132150282458,
 -4.8721990398914885,
 -4.804751719924984,
 -3.9188258418238293,
 -3.8817593727512154,
 -3.199235071571312,
 -3.014338948255498,
 -2.727110646151037,
 -2.672859135117788,
 -2.638976614808112,
 -2.5625208595153706,
 -2.556766291191558,
 -2.395656965363937,
 -2.3660289545112465,
 -2.3240216219892624,
 -2.2287497783768884,
 -2.0914575909151494,
 -1.898824313553384,
 -1.8669544441886399,
 -1.7671164120620162,
 -1.563169514910168,
 -1.479543663381669,
 -1.4114255709888144,
 -1.3879614189807143,
 -1.3273324368323443,
 -1.325957612916584,
 -1.3171615588150163,
 -1.2158957872150304,
 -1.044936415353959,
 -1.030428355870944,
 -1.0197620956039748,
 -0.9778763099371308,
 -0.8194895542576276,
 -0.6729316989429469,
 -0.6321024188947268,
 -0.4987673081174447,
 -0.43053023281433633,
 -0.3959092587800215,
 -0.2633283377411014,
 -0.24122804461618944,
 -0.2188898242661734,
 -0.16982468927432448,
 -0.10529526009721064,
 0.039087218859630325,
 

In [ ]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[-0.9999964514034569,
 -0.9999952870402741,
 -0.9999450739755725,
 -0.9998827625883405,
 -0.9998658327423809,
 -0.9992111221141182,
 -0.9991504437752106,
 -0.9966773269373891,
 -0.9951942227743997,
 -0.9914800362529439,
 -0.9905082120560538,
 -0.989846085045611,
 -0.9881783525701456,
 -0.9880423278144481,
 -0.9835336113046313,
 -0.9825371670343439,
 -0.9810211635757432,
 -0.977083016875023,
 -0.9699504262779237,
 -0.9561366944651283,
 -0.9533172156099823,
 -0.9432925177858063,
 -0.9159324475834495,
 -0.9013824554920036,
 -0.8877964760642557,
 -0.8827215740438117,
 -0.8685958520535778,
 -0.8682578726859077,
 -0.8660763102775821,
 -0.8384393317396425,
 -0.7798299358959044,
 -0.7740800818364428,
 -0.7697696183868427,
 -0.7521451057467816,
 -0.6747919533471016,
 -0.5869050430191581,
 -0.5594981957380375,
 -0.4611471574563284,
 -0.40576433675852963,
 -0.37644333625872295,
 -0.2574059952303656,
 -0.23665535301231713,
 -0.21545967690400783,
 -0.16821070055911627,
 -0.10490783875205484,
 0.039

In [ ]:
df = pd.DataFrame({'data': data, 
                   'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -6.621052  -0.999996
1 -6.479170  -0.999995
2 -5.251322  -0.999945
3 -4.872199  -0.999883
4 -4.804752  -0.999866

In [ ]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [ ]:
# dobra dla klasyfikacji wieloklasowej
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [ ]:
# 4 próbki i w ostatniej wartswie 5 klas
data = np.random.randn(4, 5)
data

array([[ 0.38593 , -2.009427,  1.073051, -0.760349, -0.793825],
       [-0.677732, -0.190475, -0.475178,  0.230409,  0.184846],
       [-0.374103,  0.47311 , -0.572242,  0.84135 , -1.026342],
       [-0.310216, -0.796961, -0.315786, -0.343184, -1.875972]])

In [ ]:
# w wektorach są p-twa przynależności danej próbki do poszczególnej klasy
np.exp(data)

array([[1.470982, 0.134065, 2.924289, 0.467503, 0.452112],
       [0.507767, 0.826567, 0.621774, 1.259115, 1.203034],
       [0.687906, 1.604978, 0.564259, 2.319496, 0.358315],
       [0.733288, 0.450697, 0.729216, 0.709508, 0.153206]])

In [ ]:
np.sum(np.exp(data), axis=0)

array([3.399943, 3.016306, 4.839538, 4.755622, 2.166667])

In [ ]:
np.exp(data) / np.sum(np.exp(data), axis=0)

array([[0.432649, 0.044447, 0.60425 , 0.098305, 0.208667],
       [0.149346, 0.274033, 0.128478, 0.264763, 0.555246],
       [0.202329, 0.5321  , 0.116594, 0.487738, 0.165376],
       [0.215677, 0.14942 , 0.150679, 0.149194, 0.07071 ]])

In [ ]:
results = softmax(data)
results
# w pierwszej próbce byłaby to klasa z indeksem 2 bo najwyższy wynik 0.60425

array([[0.432649, 0.044447, 0.60425 , 0.098305, 0.208667],
       [0.149346, 0.274033, 0.128478, 0.264763, 0.555246],
       [0.202329, 0.5321  , 0.116594, 0.487738, 0.165376],
       [0.215677, 0.14942 , 0.150679, 0.149194, 0.07071 ]])

In [ ]:
# w każdym wektorze p-twa sumują się do 1 (czemu sumuje kolumnami skoro próbki to wiersze)
np.sum(results, axis=0)

array([1., 1., 1., 1., 1.])