<a href="https://colab.research.google.com/github/KamilBienias/neural-network-course/blob/main/02_basics/03_loss_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Funkcje Straty - Loss Function:
1. [Entropia rozkładu prawdopodobieństwa](#a0)
2. [Binarna entropia krzyżowa - Binary Crossentropy](#a1)
3. [Kategoryczna entropia krzyżowa - Categorical Crossentropy](#a0)

#### <a name='a0'></a> 1. Entropia rozkładu prawdopodobieństwa
$$Entropia = - \sum_{i}p_{i} * log(p_{i})$$
Gdzie $p_{i}$ to prawdopodobieństwo zajścia $i$-tego zdarzenia. Entropia charakteryzuje możliwość oddawania informacji przez źródło. Inaczej jest to miara nieokreśloności/niepewności. Średnie zdziwienie (wartość oczekiwana zdziwienia)

In [ ]:
# Użyj poniższego polecenia jeśli używasz innego środowiska niż Google Colab
# !pip install --upgrade -q tensorflow

# Istnieje tylko w Google Colab, wersja szybsza ;)
%tensorflow_version 2.x

In [ ]:
# ######################################################
# Etap 5. Odcinek: Funkcje straty - przykłady.

import numpy as np
np.set_printoptions(precision=6, suppress=True)

def entropy(labels, base=None):
    from math import log, e
    n_labels = len(labels)
    
    if n_labels <= 1:
        return 0
    
    value, counts = np.unique(labels, return_counts=True)
    probs = counts / n_labels
    n_classes = np.count_nonzero(probs)
    
    if n_classes <= 1:
        return 0
    
    ent = 0.
    
    base = e if base is None else base
    for i in probs:
        ent -= i * log(i, base)
    return ent


labels = [1,3,5,2,3,5,3,2,1,3,4,5]
entropy(labels)

1.5171063970610277

In [ ]:
labels = [3, 3, 3, 3, 3, 3, 3]
entropy(labels)

0

#### <a name='a1'></a> 2. Binarna entropia krzyżowa - Binary Crossentropy
$$Binary\ CrossEntropy = - \frac{1}{N}\sum_{i=1}^{N}(y_{i}*log(p(y_{i})) + (1-y_{i}) * log(1-p(y_{i}))$$

In [ ]:
from tensorflow.keras.losses import binary_crossentropy

y_true = np.array([1, 0, 1, 1, 0, 1], dtype='float')
y_pred = np.array([0, 0, 1, 1, 0, 1], dtype='float')

binary_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=2.5708247450663957>

#### <a name='a2'></a> 3. Kategoryczna entropia krzyżowa - Categorical Crossentropy
$$Categorical\ CrossEntropy= - \sum_{i}y_{i} * log(p(y_{i})) $$

In [ ]:
from tensorflow.keras.losses import categorical_crossentropy

y_true = np.array([1, 0, 1, 1, 2, 0, 1, 1, 2], dtype='float')
y_pred = np.array([0, 0, 1, 1, 2, 0, 1, 2, 2], dtype='float')

categorical_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=30.23015636684835>

In [ ]:
y_true = np.array([0, 0, 1, 1, 2, 0, 1, 1, 2], dtype='float')
y_pred = np.array([0, 1, 1, 2, 0, 1, 1, 2, 1], dtype='float')

categorical_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=44.03324440481406>